global:

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:

  # Send Watchdog alerts to the void
  - match:
      alertname: Watchdog
    receiver: 'null'
  
  # Send all other alerts to the default receiver
  - receiver: 'default'

receivers:
  # null receiver does not send notifications anywhere
  - name: 'null'
  - name: 'default'
