version: '3.8'
networks:
  prometheus:
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - prometheus
    ports:
      - 9090:9090

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'      
    networks:
      - prometheus
    ports:
      - 9093:9093

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - prometheus
    ports:
      - 9100:9100

  alertmanager-logger:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "alertmanager-logger:latest"
    container_name: alertmanager-logger
    image: alertmanager-logger:latest
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - prometheus
    ports:
      - 9500:9500

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - prometheus
    ports:
      - 9501:8080

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   networks:
  #     - prometheus
  #   ports:
  #     - 3000:3000
