groups:
  - name: node_exporter
    rules:
      - alert: BogusAlert
        expr: up{job="node-exporter"} != 1
        labels:
          severity: critical
        annotations:
          summary: "Bogus Alert"

      - alert: SecondBogusAlert
        expr: sum(node_disk_info) > 1
        labels:
          severity: critical
        annotations:
          summary: "Second bogus Alert"

      - alert: ThirdBogusAlert
        expr: up{job="cadvisor"} != 1
        labels:
          severity: warning
        annotations:
          summary: "Third bogus Alert"

      - alert: ForthBogusAlert
        expr: up{job="prometheus"} != 1
        labels:
          severity: critical
        annotations:
          summary: "Forth bogus Alert"
