global:

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 20s
  receiver: 'default'
  routes:

  # Send Watchdog alerts to the void
  - match:
      alertname: Watchdog
    receiver: 'null'

receivers:
  # null receiver does not send notifications anywhere
  - name: 'null'

  - name: 'default'
    webhook_configs:
      - url: 'http://alertmanager-logger:9500/alerts'
